/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-18 03:35:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/app/board/../main/header.jsp", Long.valueOf(1605587529020L));
    _jspx_dependants.put("jar:file:/C:/Users/soonho/Desktop/it/JSP/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Fromme/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1604661035002L));
    _jspx_dependants.put("/app/board/../main/banner.jsp", Long.valueOf(1605056909727L));
    _jspx_dependants.put("jar:file:/C:/Users/soonho/Desktop/it/JSP/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Fromme/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/app/board/../main/footer.jsp", Long.valueOf(1604661046352L));
    _jspx_dependants.put("/app/board/../main/src_forInclude.html", Long.valueOf(1604665015091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-KR\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<title>FROmme - 내 손으로 만드는 특별한 순간</title>\r\n");
      out.write("\t\t");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- template css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/responsee.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/template-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/map.css\">\r\n");
      out.write("<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Playfair+Display&subset=latin,latin-ext'>\r\n");
      out.write("<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800&subset=latin,latin-ext'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" >\r\n");
      out.write("\r\n");
      out.write("<!-- templete jquery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- templete script -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/template-scripts.js\"></script>\r\n");
      out.write("<script \tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script \tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets//js/responsee.js\"></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script>var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";</script>");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/board-style.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/summernote/summernote-lite.css\">\r\n");
      out.write("\t\t<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Playfair+Display&subset=latin,latin-ext'>\r\n");
      out.write("\t\t<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800&subset=latin,latin-ext'>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/summernote/summernote-lite.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/summernote/summernote-ko-KR.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/board.js\"></script>\r\n");
      out.write("\t\t<script>var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"size-1140\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!-- HEADER -->\r\n");
      out.write("\t\t<header role=\"banner\" class=\"position-absolute\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("      <!-- Top Navigation -->\r\n");
      out.write("      <nav\r\n");
      out.write("         class=\"background-transparent background-transparent-hightlight full-width sticky\">\r\n");
      out.write("         <div class=\"s-12 l-2 header-logo\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\" class=\"logo\"> <!-- Logo White Version --> <img\r\n");
      out.write("               class=\"logo-white\"\r\n");
      out.write("               src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("               <!-- Logo Dark Version --> <img class=\"logo-dark\"\r\n");
      out.write("               src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"top-nav s-12 l-10\">\r\n");
      out.write("         \r\n");
      out.write("            <ul class=\"right chevron text-dark\">\r\n");
      out.write("               <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\">Home</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/classes/ClassesList.cls?sort_type=all&sort_by=new\">Class</a></li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=1\">Board</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=3\">Community</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("               <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/map/FindGongBangList.map\">Map</a></li>\r\n");
      out.write("               ");

                  String users_id = "";
                  if(session.getAttribute("session_id") != null){
                     users_id = (String)session.getAttribute("session_id");
                  }
                  if (users_id.equals("")){
               
      out.write("\r\n");
      out.write("                  <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/login.jsp\"><b>Login</b></a></li>\r\n");
      out.write("               ");
      
                  } else {
               
      out.write("\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage.jsp?cat=5\"><b>");
      out.print(users_id );
      out.write("</b></a>\r\n");
      out.write("                     <ul>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage.jsp?cat=5\">MyPage</a></li>\r\n");
      out.write("                        ");

                           if(((int)session.getAttribute("authority")) == 1){
                        
      out.write("\r\n");
      out.write("                           <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/studio/StudioViewAction.std?cat=6\">MyStudio</a></li>\r\n");
      out.write("                           <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/UserLogout.use?cat=7\">Logout</a></li>\r\n");
      out.write("                        ");
      
                           }else{
                        
      out.write("\r\n");
      out.write("                           <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/UserLogout.use?cat=6\">Logout</a></li>\r\n");
      out.write("                        ");

                           }
                        
      out.write("\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("               ");

                  }
               
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- slide banner -->\r\n");
      out.write("\t\t<!-- MAIN -->\r\n");
      out.write("\t\t<main role=\"main\">\r\n");
      out.write("\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"margin-top-70\">\r\n");
      out.write("\t<div class=\"carousel-default owl-carousel carousel-main carousel-nav-white background-dark text-center\">\r\n");
      out.write("\t\t<div class=\"item\">\r\n");
      out.write("    \t\t<div class=\"s-12 board_banner\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/banner/event_mini_banner1.png\" alt=\"background-dark\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t<div class=\"s-12 board_banner\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/banner/event_mini_banner1.png\" alt=\"background-dark\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t<!-- MAIN -->\r\n");
      out.write("\t\t<main role=\"main\">\r\n");
      out.write("\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t<article>\r\n");
      out.write("\t\t\t\t<div class=\"board_wrapper board_write_wrapper\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardModifyOk.bo\" name=\"modifyform\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardBean.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"cat\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardBean.getCategory_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bbsview_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_catname\"><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.catname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_title\" style=\"border:none;\"><input type=\"text\" placeholder=\"제목을 입력해주세요.\" style=\"width: 100%;\" name=\"board_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardBean.getPost_title()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_id\" style=\"border:none;\">작성자 : <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardBean.getUsers_id()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"summernote\" class=\"bbs_content\" name=\"editordata\" placeholder=\"내용을 입력해주세요.\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardBean.getPost_content()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>파일 첨부</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:plusFileTag()\"><img class=\"file_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/board_images/btn_plus.png\">추가</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:minusFileTag()\"><img class=\"file_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/board_images/btn_minus.png\">삭제</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_file file_tag\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dropContainer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_file\" onclick=\"clickFile('bbs_file1')\">파일 선택</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"span_file span1\">파일을 이 곳에 드래그 해보세요.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bbs_file1\" style=\"opacity:0; margin-left:7%\" onchange=\"changeValue('bbs_file1', 'span1')\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept=\"image/*,vidio/*,audio/*,.zip,.text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_del\" onclick=\"deleteFile('bbs_file1','span1')\">첨부 삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_file file_tag\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dropContainer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_file\" onclick=\"clickFile('bbs_file2')\">파일 선택</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"span_file span2\">파일을 이 곳에 드래그 해보세요.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bbs_file2\" style=\"opacity:0; margin-left:7%\" onchange=\"changeValue('bbs_file2', 'span2')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept=\"image/*,vidio/*,audio/*,.zip,.text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_del\" onclick=\"deleteFile('bbs_file2','span2')\">첨부 삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"bbs_file file_tag\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"dropContainer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_file\" onclick=\"clickFile('bbs_file3')\">파일 선택</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"span_file span3\">파일을 이 곳에 드래그 해보세요.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bbs_file3\" style=\"opacity:0; margin-left:7%\" onchange=\"changeValue('bbs_file3', 'span3')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccept=\"image/*,vidio/*,audio/*,.zip,.text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_bbs btn_del\" onclick=\"deleteFile('bbs_file3','span3')\">첨부 삭제</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn_bbs_write\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardView.bo?&cat=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&seq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn_bbs\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:modifyBoard()\" class=\"btn_bbs\">수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</form>        \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("      <!-- Main Footer -->\r\n");
      out.write("      <section class=\"background-white full-width\">\r\n");
      out.write("        <hr class=\"break margin-top-bottom-0\" style=\"border-color: rgba(199, 199, 199, 0.8);\">\r\n");
      out.write("        <!-- Logo img -->\r\n");
      out.write("        <div class=\"margin-top-20 margin-left-right-20\" style=\"width: 20%;\">\r\n");
      out.write("       <img class=\"logo-dark\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"margin-top-bottom-0\">\r\n");
      out.write("          <div class=\"s-6 l-6\">\r\n");
      out.write("            <div class=\"margin-top-10 text-size-16 padding\">\r\n");
      out.write("              <div class=\"\" style=\"font-family: GmarketSansMedium;\">크리에이터</div>\r\n");
      out.write("              <a href=\"#\" style=\"font-family: GmarketSansMedium;\" class=\"text-size-12\">공방 등록 문의</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"s-12 l-6\">\r\n");
      out.write("            <div class=\"margin-top-10 text-size-16 padding\">\r\n");
      out.write("              <div class=\"\" style=\"font-family: GmarketSansMedium;\">고객센터 010-000-0000</div>\r\n");
      out.write("              <a href=\"#\" style=\"font-family: GmarketSansMedium;\" class=\"text-size-12\">오전 10시 ~ 오후 6시 (주말, 공휴일 제외)</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      <hr class=\"break margin-top-bottom-0\" style=\"border-color: rgba(199, 199, 199, 0.8);\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Bottom Footer -->\r\n");
      out.write("      <section class=\"padding background-white full-width \">\r\n");
      out.write("        <div class=\"Footer__AgreementInner text-size-12\" style=\"font-family: GmarketSansMedium;\">\r\n");
      out.write("          <div class=\"center margin-bottom-10\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"s-12 l-12\">\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-1\">이용약관 |</a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-2\"><b>개인정보 처리방침 |</b></a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-3\">사업자 정보 확인 |</a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-4\">제휴/협력 문의</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <p class=\"text-size-12\">\r\n");
      out.write("              (주) FROmme | 대표 홍길동 | 서울특별시 역삼동 통일로 10 세브란스빌딩 18층\r\n");
      out.write("              | 사업자등록번호 : 000-00-00000 |\r\n");
      out.write("              통신판매업신고 : 2020-서울강남-0000 |\r\n");
      out.write("              주식회사 FROmme는 전자상거래 등에서의 소비자보호에 관한 법률에 따른 통신판매업과 통신판매중개업을 영위하고 있습니다.\r\n");
      out.write("              주식회사 FROmme는 통신판매중개자로서 중개하는 통신판매에 관하여서는 통신판매의 당사자가 아니므로 어떠한 책임도 부담하지 아니합니다.\r\n");
      out.write("              created by Team Method\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"s-12 l-12\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("      </section>");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<script>var summernoteImages = [];</script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$('#summernote').summernote({\r\n");
      out.write("\t\t\t\t\ttoolbar: [\r\n");
      out.write("\t\t\t\t\t\t// [groupName, [list of button]]\r\n");
      out.write("\t\t\t\t\t\t['fontname', ['fontname']],\r\n");
      out.write("\t\t\t\t\t\t['fontsize', ['fontsize']],\r\n");
      out.write("\t\t\t\t\t\t['style', ['bold', 'italic', 'underline','strikethrough', 'clear']],\r\n");
      out.write("\t\t\t\t\t\t['color', ['forecolor','color']],\r\n");
      out.write("\t\t\t\t\t\t['table', ['table']],\r\n");
      out.write("\t\t\t\t\t\t['para', ['ul', 'ol', 'paragraph']],\r\n");
      out.write("\t\t\t\t\t\t['height', ['height']],\r\n");
      out.write("\t\t\t\t\t\t['insert',['picture','link','video']],\r\n");
      out.write("\t\t\t\t\t\t['view', ['fullscreen', 'help']]\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\tfontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New','맑은 고딕','궁서','굴림체','굴림','돋음체','바탕체'],\r\n");
      out.write("\t\t\t\t\tfontSizes: ['8','9','10','11','12','14','16','18','20','22','24','28','30','36','50','72'],\r\n");
      out.write("\t\t\t\t\theight: 300,                 // 에디터 높이\r\n");
      out.write("\t\t\t\t\tminHeight: null,             // 최소 높이\r\n");
      out.write("\t\t\t\t\tmaxHeight: null,             // 최대 높이\r\n");
      out.write("\t\t\t\t\tfocus: true,                  // 에디터 로딩후 포커스를 맞출지 여부\r\n");
      out.write("\t\t\t\t\tlang: \"ko-KR\",\t\t\t\t\t// 한글 설정\r\n");
      out.write("\t\t\t\t\tplaceholder: '내용을 입력해 주세요.',\r\n");
      out.write("\t\t\t\t\tcallbacks: {\r\n");
      out.write("\t\t\t\t           onImageUpload : function(files, editor, welEditable) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t                for(var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t\t\t\t                        sendFile(files[i], this);\r\n");
      out.write("\t\t\t\t               }\r\n");
      out.write("\t\t\t\t           }\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /app/board/boardModify.jsp(22,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("category_no");
      // /app/board/boardModify.jsp(22,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.category_no}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /app/board/boardModify.jsp(23,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("boardBean");
      // /app/board/boardModify.jsp(23,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.boardBean}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
