/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-23 01:54:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 우리 페이지 로고 -->\r\n");
      out.write("    <div class=\"left-sidebar-pro\">\r\n");
      out.write("        <nav id=\"sidebar\" class=\"\">\r\n");
      out.write("            <div class=\"sidebar-header\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/indexData.adm\"><img class=\"main-logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/img/logo/logo_3.png\" alt=\"\" /></a>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"nalika-profile\">\r\n");
      out.write("\t\t\t\t<div class=\"profile-dtl\">\r\n");
      out.write("                    <!-- gravatar 연동? -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/img/notification/4.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <div class=\"left-custom-menu-adp-wrap comment-scrollbar\">\r\n");
      out.write("                <nav class=\"sidebar-nav left-sidebar-menu-pro\">\r\n");
      out.write("                    <ul class=\"metismenu\" id=\"menu1\">\r\n");
      out.write("                        <li class=\"\" onclick=\"\">\r\n");
      out.write("                            <a class=\"has-arrow\" href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <i class=\"icon nalika-home icon-wrap\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <span class=\"mini-click-non\">데이터 관리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/studioApplyList.adm\"><span class=\"mini-sub-pro\">공방주 승인</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/classList.adm\"><span class=\"mini-sub-pro\">클래스 목록</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/userList.adm\"><span class=\"mini-sub-pro\">유저 목록</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board.adm?category=2\"><span class=\"mini-sub-pro\">건의사항 게시판</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board.adm?category=3\"><span class=\"mini-sub-pro\">내 작품 자랑 게시판</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board.adm?category=4\"><span class=\"mini-sub-pro\">중고 거래 게시판</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("                                <li><a title=\"Product List\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/board.adm?category=1\"><span class=\"mini-sub-pro\">공지사항</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"has-arrow\" href=\"mailbox.html\" aria-expanded=\"false\"><i class=\"icon nalika-mail icon-wrap\"></i> <span class=\"mini-click-non\">쪽지함</span></a>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"false\">\r\n");
      out.write("                                <li><a title=\"Inbox\" href=\"#\"><span class=\"mini-sub-pro\">쪽지함</span></a></li>\r\n");
      out.write("                                <li><a title=\"Compose Mail\" href=\"#\"><span class=\"mini-sub-pro\">쪽지 보내기</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"has-arrow\" href=\"#\" aria-expanded=\"false\"><i class=\"icon nalika-bar-chart icon-wrap\"></i> <span class=\"mini-click-non\">차트</span></a>\r\n");
      out.write("                            <ul class=\"submenu-angle\" aria-expanded=\"false\">\r\n");
      out.write("                                <li><a title=\"Bar Charts\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/viewChart.jsp\"><span class=\"mini-sub-pro\">방문 차트</span></a></li>\r\n");
      out.write("                                <li><a title=\"Line Charts\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/admin/classChart.jsp\"><span class=\"mini-sub-pro\">예약 차트</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Start Welcome area -->\r\n");
      out.write("    <div class=\"all-content-wrapper\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"logo-pro\">\r\n");
      out.write("                        <!-- 우리 로고 -->\r\n");
      out.write("                        <a href=\"index.jsp\"><img class=\"main-logo\" src=\"img/logo/logo_3.png\" alt=\"\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-advance-area\">\r\n");
      out.write("            <div class=\"header-top-area\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                            <div class=\"header-top-wraper\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-lg-1 col-md-0 col-sm-1 col-xs-12\">\r\n");
      out.write("                                        <div class=\"menu-switcher-pro\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6 col-md-7 col-sm-6 col-xs-12\">\r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-5 col-md-5 col-sm-12 col-xs-12\">\r\n");
      out.write("                                        <div class=\"header-right-info\">\r\n");
      out.write("                                            <ul class=\"nav navbar-nav mai-top-nav header-right-menu\">\r\n");
      out.write("                                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                    <a href=\"#\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\" class=\"nav-link dropdown-toggle\"><i class=\"icon nalika-mail\" aria-hidden=\"true\"></i><span class=\"indicator-ms\"></span></a>\r\n");
      out.write("                                                    <div role=\"menu\" class=\"author-message-top dropdown-menu animated zoomIn\">\r\n");
      out.write("                                                        <div class=\"message-single-top\">\r\n");
      out.write("                                                            <h1>쪽지</h1>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <ul class=\"message-menu\">\r\n");
      out.write("                                                            <!-- 관리자에게 온 쪽지 (최대 4개)-->\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                        <div class=\"message-view\">\r\n");
      out.write("                                                            <!-- 메일함이 완성돠면 링크 추가 -->\r\n");
      out.write("                                                            <a href=\"#\">모든 쪽지 보기</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"nav-item\"><a href=\"#\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\" class=\"nav-link dropdown-toggle\"><i class=\"icon nalika-alarm\" aria-hidden=\"true\"></i><span class=\"indicator-nt\"></span></a>\r\n");
      out.write("                                                    <div role=\"menu\" class=\"notification-author dropdown-menu animated zoomIn\">\r\n");
      out.write("                                                        <div class=\"notification-single-top\">\r\n");
      out.write("                                                            <h1>알림</h1>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <ul class=\"notification-menu\">\r\n");
      out.write("                                                            <!-- 관리자에게 오는 알림판 (최대 4개)-->\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                        <div class=\"notification-view\">\r\n");
      out.write("                                                            <a href=\"#\">모든 알림 보기</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"nav-item\">\r\n");
      out.write("                                                    <a href=\"#\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\" class=\"nav-link dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"admin-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-down-arrow nalika-angle-dw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("                                                    <ul role=\"menu\" class=\"dropdown-header-top author-log dropdown-menu animated zoomIn\">\r\n");
      out.write("                                                        <!-- 내 정보 보기로 가는 링크-->\r\n");
      out.write("                                                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\"><span class=\"icon nalika-settings author-log-ic\"></span>메인 페이지</a>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/UserLogout.use\"><span class=\"icon nalika-unlocked author-log-ic\"></span>로그 아웃</a>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"nav-item nav-setting-open\"><a href=\"#\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\" class=\"nav-link dropdown-toggle\"><i class=\"icon nalika-menu-task\"></i></a>\r\n");
      out.write("                                                    <div role=\"menu\" class=\"admintab-wrap menu-setting-wrap menu-setting-wrap-bg dropdown-menu animated zoomIn\">\r\n");
      out.write("                                                        <ul class=\"nav nav-tabs custon-set-tab\">\r\n");
      out.write("                                                            <li class=\"active\"><a data-toggle=\"tab\" href=\"#Notes\">News</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><a data-toggle=\"tab\" href=\"#Projects\">Activity</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><a data-toggle=\"tab\" href=\"#Settings\">Settings</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"tab-content custom-bdr-nt\">\r\n");
      out.write("                                                            <div id=\"Notes\" class=\"tab-pane fade in active\">\r\n");
      out.write("                                                                <div class=\"notes-area-wrap\">\r\n");
      out.write("                                                                    <div class=\"note-heading-indicate\">\r\n");
      out.write("                                                                        <h2><i class=\"icon nalika-chat\"></i> Latest News</h2>\r\n");
      out.write("                                                                        <p>You have 10 New News.</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"notes-list-area notes-menu-scrollbar\">\r\n");
      out.write("                                                                        \r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div id=\"Projects\" class=\"tab-pane fade\">\r\n");
      out.write("                                                                <div class=\"projects-settings-wrap\">\r\n");
      out.write("                                                                    <div class=\"note-heading-indicate\">\r\n");
      out.write("                                                                        <h2><i class=\"icon nalika-happiness\"></i> Recent Activity</h2>\r\n");
      out.write("                                                                        <p> You have 20 Recent Activity.</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"project-st-list-area project-st-menu-scrollbar\">\r\n");
      out.write("                                                                        \r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div id=\"Settings\" class=\"tab-pane fade\">\r\n");
      out.write("                                                                <div class=\"setting-panel-area\">\r\n");
      out.write("                                                                    <div class=\"note-heading-indicate\">\r\n");
      out.write("                                                                        <h2><i class=\"icon nalika-gear\"></i> Settings Panel</h2>\r\n");
      out.write("                                                                        <p> You have 20 Settings. 5 not completed.</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <ul class=\"setting-panel-list\">\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Show notifications</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Disable Chat</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example3\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Enable history</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example4\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Show charts</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example7\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Update everyday</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" checked=\"\" class=\"onoffswitch-checkbox\" id=\"example2\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Global search</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" checked=\"\" class=\"onoffswitch-checkbox\" id=\"example6\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                        <li>\r\n");
      out.write("                                                                            <div class=\"checkbox-setting-pro\">\r\n");
      out.write("                                                                                <div class=\"checkbox-title-pro\">\r\n");
      out.write("                                                                                    <h2>Offline users</h2>\r\n");
      out.write("                                                                                    <div class=\"ts-custom-check\">\r\n");
      out.write("                                                                                        <div class=\"onoffswitch\">\r\n");
      out.write("                                                                                            <input type=\"checkbox\" name=\"collapsemenu\" checked=\"\" class=\"onoffswitch-checkbox\" id=\"example5\">\r\n");
      out.write("                                                                                            <label class=\"onoffswitch-label\" for=\"example5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                    </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </li>\r\n");
      out.write("                                                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Mobile Menu start -->\r\n");
      out.write("            <div class=\"mobile-menu-area\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                            <div class=\"mobile-menu\">\r\n");
      out.write("                                <nav id=\"dropdown\">\r\n");
      out.write("                                    <ul class=\"mobile-menu-nav\">\r\n");
      out.write("                                        <li><a data-toggle=\"collapse\" data-target=\"#Charts\" href=\"#\">데이터 목록<span class=\"admin-project-icon nalika-icon nalika-down-arrow\"></span></a>\r\n");
      out.write("                                            <ul class=\"collapse dropdown-header-top\">\r\n");
      out.write("                                                <li><a href=\"product-list.jsp\">클래스 목록</a></li>\r\n");
      out.write("                                                <li><a href=\"user_list.jsp\">유저 목록</a></li>\r\n");
      out.write("                                                <li><a href=\"noticeList.jsp\">공지사항 목록</a></li>\r\n");
      out.write("                                                <li><a href=\"suggestBoard.jsp\">건의 사항 게시판</a></li>\r\n");
      out.write("                                                <li><a href=\"introduceBoard.jsp\">내 작품 자랑 게시판</a></li>\r\n");
      out.write("                                                <li><a href=\"tradeBoard.jsp\">중고 거래 게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a data-toggle=\"collapse\" data-target=\"#demo\" href=\"#\">메일함<span class=\"admin-project-icon nalika-icon nalika-down-arrow\"></span></a>\r\n");
      out.write("                                            <ul id=\"demo\" class=\"collapse dropdown-header-top\">\r\n");
      out.write("                                                <li><a href=\"mailbox.html\">Inbox</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"mailbox-view.html\">View Mail</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"mailbox-compose.html\">Compose Mail</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <li><a data-toggle=\"collapse\" data-target=\"#Chartsmob\" href=\"#\">차트<span class=\"admin-project-icon nalika-icon nalika-down-arrow\"></span></a>\r\n");
      out.write("                                            <ul id=\"Chartsmob\" class=\"collapse dropdown-header-top\">\r\n");
      out.write("                                                <li><a href=\"viewChart.jsp\">방문 차트</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"classChart.jsp\">예약 차트</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Mobile Menu end -->\r\n");
      out.write("            <div class=\"breadcome-area\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                            <div class=\"breadcome-list\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("                                        <div class=\"breadcomb-wp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"breadcomb-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"breadcomb-ctn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2>[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("] 님 안녕하세요</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("                                      \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- 메인 컨텐츠 표시구간 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
