/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-19 01:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/app/user/../main/src_forInclude.html", Long.valueOf(1604665015091L));
    _jspx_dependants.put("/app/user/../main/header.jsp", Long.valueOf(1605748641331L));
    _jspx_dependants.put("/app/user/../main/footer.jsp", Long.valueOf(1604661046352L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-KR\">\r\n");
      out.write("  <head>\r\n");
      out.write("  \t<style type=\"text/css\">\r\n");
      out.write("  \t\t#box{border:1px solid black;}\r\n");
      out.write("  \t\t#postcodify_search_button{border:1px solid black;}\r\n");
      out.write("  \t\t#body_back{background-image:url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/banner/background_body.png\");}\r\n");
      out.write("  \t\t.circle{\r\n");
      out.write("  \t\t\twidth:100px;\r\n");
      out.write("  \t\t\theight:100px;\r\n");
      out.write("  \t\t\tbackground:gray;\r\n");
      out.write("  \t\t\tborder-radius:50%;\r\n");
      out.write("  \t\t\tmargin-right:9%;\r\n");
      out.write("  \t\t\ttext-align:center;\r\n");
      out.write("  \t\t\tline-height:100px;\r\n");
      out.write("  \t\t\tfloat:left;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\t.circle-back{\r\n");
      out.write("  \t\t\twidth:100px;\r\n");
      out.write("  \t\t\theight:100px;\r\n");
      out.write("  \t\t\tbackground:gray;\r\n");
      out.write("  \t\t\tborder-radius:50%;\r\n");
      out.write("  \t\t\ttext-align:center;\r\n");
      out.write("  \t\t\tline-height:100px;\r\n");
      out.write("  \t\t\tfloat:left;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\t.arrow{\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.arrow::after{\r\n");
      out.write("\t\t\tcontent:\"\";\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\twidth:10px;\r\n");
      out.write("\t\t\theight:10px;\r\n");
      out.write("\t\t\tborder-top:4px solid #333;\r\n");
      out.write("\t\t\tborder-right:4px solid #333;\r\n");
      out.write("\t\t\t-webkit-transform: rotate(45deg);\r\n");
      out.write("\t\t\ttransform: rotate(45deg);\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tmargin:auto;\r\n");
      out.write("\t\t\tright:50px;\r\n");
      out.write("\t\t\ttop:50%;\r\n");
      out.write("\t\t\tmargin-top:-7px;\r\n");
      out.write("\t\t}\r\n");
      out.write("  \t</style>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>회원정보 / FROmme - 내 손으로 만드는 특별한 순간</title>\r\n");
      out.write("\t");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- template css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/responsee.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/template-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/map.css\">\r\n");
      out.write("<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Playfair+Display&subset=latin,latin-ext'>\r\n");
      out.write("<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800&subset=latin,latin-ext'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" >\r\n");
      out.write("\r\n");
      out.write("<!-- templete jquery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- templete script -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/template-scripts.js\"></script>\r\n");
      out.write("<script \tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script \tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets//js/responsee.js\"></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script>var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";</script>");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/css/board-style.css\">\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"size-1140\">\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("    <header role=\"banner\" class=\"position-absolute\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<!-- Top Navigation -->\r\n");
      out.write("\t\t<nav\r\n");
      out.write("\t\t\tclass=\"background-transparent background-transparent-hightlight full-width sticky\">\r\n");
      out.write("\t\t\t<div class=\"s-12 l-2 header-logo\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\" class=\"logo\"> <!-- Logo White Version --> <img\r\n");
      out.write("\t\t\t\t\tclass=\"logo-white\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Logo Dark Version --> <img class=\"logo-dark\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"top-nav s-12 l-10\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"right chevron text-dark\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/main/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/classes/classesList.cls\">Class</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=1\">Board</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=2\">문의사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=3\">Community</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=3\">내작품자랑</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/BoardList.bo?cat=4\">중고거래</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../user/map.html\">Map</a></li>\r\n");
      out.write("\t\t\t\t\t");

						String users_id = "";
						if(session.getAttribute("session_id") != null){
							users_id = (String)session.getAttribute("session_id");
						}
						if (users_id.equals("")){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/login.jsp\"><b>Login</b></a></li>\r\n");
      out.write("\t\t\t\t\t");
		
						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(session.getAttribute("authority") == null){
									session.setAttribute("authority", 0);
								}
								if(((int)session.getAttribute("authority") == 1)){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage_studio.jsp?cat=5\"><b>");
      out.print(users_id );
      out.write("</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage_studio.jsp?cat=5\">MyPage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myStudio.jsp?cat=6\">MyStudio</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/UserLogout.use?cat=7\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
		
									}else{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage.jsp?cat=5\"><b>");
      out.print(users_id );
      out.write("</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/user/myPage.jsp?cat=5\">MyPage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/UserLogout.use?cat=6\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- MAIN -->\r\n");
      out.write("\t  <main role=\"main\">\r\n");
      out.write("\t    <!-- Main Header -->\r\n");
      out.write("\t    <header>\r\n");
      out.write("\t      <div class=\"margin-top-70\">\r\n");
      out.write("\t        <div class=\"carousel-default owl-carousel carousel-main carousel-nav-white background-dark text-center\">\r\n");
      out.write("\t\r\n");
      out.write("\t          <div class=\"item\">\r\n");
      out.write("\t            <div class=\"s-12\">\r\n");
      out.write("\t              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/banner/event_mini_banner1.png\" alt=\"background-dark\">\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t\r\n");
      out.write("\t          <div class=\"item\">\r\n");
      out.write("\t            <div class=\"s-12\">\r\n");
      out.write("\t              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/banner/event_mini_banner1.png\" alt=\"background-dark\">\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </header>\r\n");
      out.write("\t    <div class=\"line\"> \t\r\n");
      out.write("\t    </div>\r\n");
      out.write("    <!-- MAIN -->\r\n");
      out.write("    <main role=\"main\">\r\n");
      out.write("      <!-- Content -->\r\n");
      out.write("      <article>\r\n");
      out.write("\t\t<div class=\"section background-white\" id=\"body_back\">\r\n");
      out.write("\t\t<div style=\"width:60%; margin:auto; font-family: GmarketSansMedium;\">\r\n");
      out.write("\t\t<div style=\"width:100%; height:1000px;\">\r\n");
      out.write("\t\t\t<h1 style=\"color:white; text-align:center;\">회　원　가　입</h1>\r\n");
      out.write("\t\t\t<div style=\"background-color:white; height:200px; margin:0 auto; margin-bottom:20px;\">\r\n");
      out.write("\t\t\t\t<br><h4 style=\"margin-left: 5%;\">가입 안내</h4>\r\n");
      out.write("\t\t\t\t<div style=\"width:80%; margin:auto;\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:white;\">약관 동의</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:white;\">개인정보입력</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"circle-back\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:white;\">회원가입</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"background-color:white; height:800px; margin:0 auto; margin-bottom:20px;\">\r\n");
      out.write("\t\t\t\t<br><h4 style=\"margin-left: 5%;\">이용약관동의</h4>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left:5%;\">\r\n");
      out.write("\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>서비스 이용약관</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea readonly=\"\" rows=\"10;\" cols=\"100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("          <div class=\"line\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      </article>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("  <!-- FOOTER -->\r\n");
      out.write("  <footer>\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("      <!-- Main Footer -->\r\n");
      out.write("      <section class=\"background-white full-width\">\r\n");
      out.write("        <hr class=\"break margin-top-bottom-0\" style=\"border-color: rgba(199, 199, 199, 0.8);\">\r\n");
      out.write("        <!-- Logo img -->\r\n");
      out.write("        <div class=\"margin-top-20 margin-left-right-20\" style=\"width: 20%;\">\r\n");
      out.write("       <img class=\"logo-dark\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/img/logo-dark.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"margin-top-bottom-0\">\r\n");
      out.write("          <div class=\"s-6 l-6\">\r\n");
      out.write("            <div class=\"margin-top-10 text-size-16 padding\">\r\n");
      out.write("              <div class=\"\" style=\"font-family: GmarketSansMedium;\">크리에이터</div>\r\n");
      out.write("              <a href=\"#\" style=\"font-family: GmarketSansMedium;\" class=\"text-size-12\">공방 등록 문의</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"s-12 l-6\">\r\n");
      out.write("            <div class=\"margin-top-10 text-size-16 padding\">\r\n");
      out.write("              <div class=\"\" style=\"font-family: GmarketSansMedium;\">고객센터 010-000-0000</div>\r\n");
      out.write("              <a href=\"#\" style=\"font-family: GmarketSansMedium;\" class=\"text-size-12\">오전 10시 ~ 오후 6시 (주말, 공휴일 제외)</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      <hr class=\"break margin-top-bottom-0\" style=\"border-color: rgba(199, 199, 199, 0.8);\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Bottom Footer -->\r\n");
      out.write("      <section class=\"padding background-white full-width \">\r\n");
      out.write("        <div class=\"Footer__AgreementInner text-size-12\" style=\"font-family: GmarketSansMedium;\">\r\n");
      out.write("          <div class=\"center margin-bottom-10\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"s-12 l-12\">\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-1\">이용약관 |</a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-2\"><b>개인정보 처리방침 |</b></a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-3\">사업자 정보 확인 |</a>\r\n");
      out.write("              <a href=\"#\" target=\"_blank\" rel=\"noreferrer\" class=\"Footer__AgreementLink-4\">제휴/협력 문의</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <p class=\"text-size-12\">\r\n");
      out.write("              (주) FROmme | 대표 홍길동 | 서울특별시 역삼동 통일로 10 세브란스빌딩 18층\r\n");
      out.write("              | 사업자등록번호 : 000-00-00000 |\r\n");
      out.write("              통신판매업신고 : 2020-서울강남-0000 |\r\n");
      out.write("              주식회사 FROmme는 전자상거래 등에서의 소비자보호에 관한 법률에 따른 통신판매업과 통신판매중개업을 영위하고 있습니다.\r\n");
      out.write("              주식회사 FROmme는 통신판매중개자로서 중개하는 통신판매에 관하여서는 통신판매의 당사자가 아니므로 어떠한 책임도 부담하지 아니합니다.\r\n");
      out.write("              created by Team Method\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"s-12 l-12\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("      </section>");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/responsee.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/assets/js/template-scripts.js\"></script>\r\n");
      out.write("  <script src=\"member.js\"></script>\r\n");
      out.write("  <script src=\"//code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("  <script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("  <script> $(function() { $(\"#postcodify_search_button\").postcodifyPopUp(); }); </script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\t var naver_id_login = new naver_id_login(\"YOUR_CLIENT_ID\", \"YOUR_CALLBACK_URL\");\r\n");
      out.write("\t // 접근 토큰 값 출력\r\n");
      out.write("\t alert(naver_id_login.oauthParams.access_token);\r\n");
      out.write("\t // 네이버 사용자 프로필 조회\r\n");
      out.write("\t naver_id_login.get_naver_userprofile(\"naverSignInCallback()\");\r\n");
      out.write("\t // 네이버 사용자 프로필 조회 이후 프로필 정보를 처리할 callback function\r\n");
      out.write("\t function naverSignInCallback() {\r\n");
      out.write("\t   alert(naver_id_login.getProfileData('email'));\r\n");
      out.write("\t   alert(naver_id_login.getProfileData('nickname'));\r\n");
      out.write("\t   alert(naver_id_login.getProfileData('age'));\r\n");
      out.write("\t }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
